#!/bin/bash
# ralph-research wonder.sh — bootstrap candidate interpretations for a seed.
# Optional helper: lets the skill reuse a deterministic Wonder pass.
# The skill itself can also call Claude directly with the WONDER_SYSTEM prompt.
#
# Usage:
#   wonder.sh --seed "<seed>" [--out <path>]
#
# If --out is given, writes JSON array to that path. Otherwise prints to stdout.

set -euo pipefail

SEED=""
OUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seed) SEED="${2:-}"; shift 2 ;;
    --out) OUT="${2:-}"; shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "❌ unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$SEED" ]]; then echo "❌ --seed required" >&2; exit 2; fi

# Wonder is driven by Claude (Opus) at skill time. This helper just produces a
# structured reminder so the skill can paste it into a Claude call.
cat <<JSON
{
  "_hint": "Wonder candidates will be generated by Claude (Opus) using WONDER_SYSTEM. This file is a placeholder; replace with actual JSON output.",
  "seed": $(printf '%s' "$SEED" | python3 -c 'import sys,json; print(json.dumps(sys.stdin.read()))'),
  "instruction": "Generate 3-6 interpretations as JSON array. Each: {label, claim, signal, research_angle}."
}
JSON